import { StyleSheet } from 'react-native';

export default StyleSheet.create({
// ? general styles
  container: {
    flex: 1,
    backgroundColor: '#fff',
    transformOrigin: 'center',
  },

  // ? onboarding Screens.
  onboardingButton: {
    fontFamily: 'Mulish-Regular',
    backgroundColor: '#2980B9',
    height: 50,
    width: 145,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontFamily: 'Mulish-Regular',
    fontSize: 15,
    fontWeight: '500',
    color: '#fff',
    textAlign: 'center',
  },
  onboardingButtonii: {
    fontFamily: 'Mulish-Regular',
    backgroundColor: '#D8DDEF',
    height: 50,
    width: 145,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTextii: {
    fontFamily: 'Mulish-Regular',
    fontSize: 15,
    fontWeight: '500',
    color: '#2980B9',
    textAlign: 'center',
  },
  slide: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginBottom: 28,
  },
  imagei: {
    marginTop: 63,
    width: 182,
    height: 41,
    resizeMode: 'contain',
  },
  imageii: {
    width: 270.57,
    height: 255.23,
    resizeMode: 'contain',
  },
  texti: {
    marginTop: 39,
    marginBottom: 65,
    fontSize: 26,
    color: '#2980B9',
    textAlign: 'center',
    fontFamily: 'Mulish-Regular',
  },
  textii: {
    marginTop: 79.77,
    marginBottom: 65,
    fontSize: 18,
    color: '#333',
    textAlign: 'center',
    color: '#2980B9',
    fontFamily: 'Mulish-Regular',
  },
  userReq: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 25,
    alignSelf: 'center',
  },
// ? Login Screen.
  logintitle: {
    fontFamily: 'Lato-Regular',
    fontSize: 31,
    color: '#2980B9',
    fontWeight: '400',
    marginLeft: 13,
    marginTop: 46,
    marginBottom: 15,
  },
  loginsubtitle: {
    fontFamily: 'Lato-Regular',
    fontSize: 26,
    fontWeight: '500',
    textAlign: 'center',
  },
  broimage: {
    width: 154.57,
    height: 150,
    alignSelf: 'center',
    marginTop: 33,
  },
  divider: {
    borderBottomColor: '#D8DDEF',
    borderBottomWidth: 1,
    width: '70%',
    alignSelf: 'center',
    marginTop: 19,
    marginBottom: 18,
  },
  socialButtons: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    gap: 80,
  },
  authicon: {
    width: 48,
    height: 48,
  },
  orText: {
    fontFamily: 'Mulish-Regular',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '400',
    color: '#aaa',
    marginBottom: 23,
    marginTop: 22,
  },
  emailbox: {
    borderWidth: 1,
    borderColor: '#aaa',
    flex: 1,
    justifyContent: 'center',
    borderRadius: 10,
    marginLeft: 31,
    marginRight: 17,
    paddingLeft: 16,
  },
  emailhead: {
    fontFamily: 'Mulish-Regular',
    color: '#aaa',
    margin: '0',
    padding: '0',
    fontSize: 13,
  },
  email: {
    padding: '0',
    width: 261,
    fontFamily: 'Mulish-Regular',
    marginBottom: 6,
  },
  passwordbox: {
    borderWidth: 1,
    borderColor: '#aaa',
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 10,
    marginLeft: 31,
    marginRight: 17,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  password: {
    color: '#aaa',
    fontFamily: 'Mulish-Regular',
    fontWeight: 400,
    fontSize: 13,
    marginTop: 16,
    marginBottom: 13,
  },
  eyeIcon: {
    marginVertical: 19,
  },
  loginButton: {
    height: 60,
    backgroundColor: '#2980B9',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 24,
    marginLeft: 31,
    marginRight: 17,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 500,
    fontFamily: 'Muslih-Regular',
  },
  forgotPassword: {
    textAlign: 'center',
    color: '#2980B9',
    fontSize: 18,
    fontWeight: 500,
    textDecorationLine: 'none',
    fontFamily: 'JosefinSans-Regular',
  },
  footerText: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: 400,
    marginTop: 37,
    marginBottom: 53,
    color: '#333',
    fontFamily: 'Mulish-Regular',
  },
  linkText: {
    color: '#2980B9',
    fontFamily: 'Mulish-Regular',
    fontSize: '15',
    fontWeight: '700',
    textDecorationLine: 'none',
  },
 

  // ? Signup Screen.
  signuptitle: {
    fontFamily: 'Lato-Regular',
    fontSize: 26,
    color: '#2980B9',
    fontWeight: 500,
    marginLeft: 38,
    marginTop: 46,
    marginBottom: 16,
  },
  signupsubtitle: {
    fontFamily: 'Lato-Regular',
    fontSize: 26,
    fontWeight: 500,
    textAlign: 'center',
    marginBottom: 27,
  },
  socialButtonsii: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    gap: 75,
    marginBottom: 12,
    marginTop: 27,
  },
  orTextii: {
    fontFamily: 'Mulish-Regular',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: 400,
    color: '#aaa',
    marginBottom: 5,
  },
  signupinputbox: {
    height: 50,
    borderWidth: 1,
    borderColor: '#aaa',
    justifyContent: 'center',
    borderRadius: 10,
    paddingLeft: 16,
    marginLeft: 24,
    marginRight: 24,
    marginBottom: 15,
  },
  emailboxii: {
    borderWidth: 1,
    borderColor: '#aaa',
    height: 50,
    justifyContent: 'center',
    borderRadius: 10,
    marginLeft: 24,
    marginRight: 24,
    marginBottom: 15,
    paddingLeft: 16,
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    marginLeft: 24,
    marginRight: 24,
    marginBottom: 15,
    flex: 1,
    position: 'relative',
    gap: 8,
  },
  countryCode: {
    height: 50,
    fontSize: 13,
    color: '#333',
    borderWidth: 1,
    borderColor: '#aaa',
    textAlign: 'center',
    borderRadius: 10,
    width: 84,
  },
  phoneInput: {
    fontSize: 13,
    color: '#333',
    width: 187.57,
    height: 21,
  },
  phoneInputbox: {
    width: 'fit-content',
    flex: 1,
    paddingLeft: 11.5,
    justifyContent: 'center',
    height: 50,
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 10,
  },
  passwordInput: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    fontSize: 16,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    marginLeft: 31,
    marginRight: 17,
  },
  eyeIconii: {
    position: 'absolute',
    right: 20,
    top: 15,
    color: 'rgba(0, 0, 0, 0.3)',
  },
  agreebox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    marginLeft: 24,
    marginRight: 24,
    marginTop: 3,
    marginBottom: 14,
    justifySelf: 'start',
    gap: 8,
    flex: 1,
  },
  checkbox: {
    marginRight: '0',
    height: 24,
    width: 24,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#aaa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  termsText: {
    fontFamily: 'Mulish-Regular',
    fontWeight: 400,
    fontSize: 13,
    color: '#aaa',
  },
  registerButton: {
    height: 60,
    backgroundColor: '#2980B9',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    marginLeft: 24,
    marginRight: 24,
  },
  footerTextii: {
    textAlign: 'center',
    fontSize: 15,
    fontWeight: 400,
    marginBottom: 37,
    color: '#333',
    fontFamily: 'Mulish-Regular',
  },

  // ? rest pass Screen.
  rpph: {
    marginLeft: 26,
    marginTop: 38,
  },
  rptopic: {
    fontFamily: 'Lato-Regular',
    fontWeight: 500,
    fontSize: 26,
    color: '#000',
    textAlign: 'center',
    marginTop: 116.37,
  },
  rpsubtopic: {
    fontFamily: 'Lato-Regular',
    fontWeight: 400,
    fontSize: 13,
    color: '#000',
    textAlign: 'center',
    marginVertical: 28,
  },
  rpemailbox: {
    borderWidth: 1,
    borderColor: '#aaa',
    height: 50,
    justifyContent: 'center',
    borderRadius: 10,
    marginLeft: 26,
    marginRight: 22,
    paddingLeft: 16,
    marginBottom: 28,
  },
  rpButton: {
    height: 60,
    backgroundColor: '#2980B9',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 346,
    marginLeft: 26,
    marginRight: 22,
  },
  // ? Verification Screen.
  verfimg: {
    width: 200,
    height: 149.02,
    justifySelf: 'center',
    alignSelf: 'center',
    marginTop: 180.37,
    marginBottom: 35,
  },
  verftext: {
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontSize: 20,
    fontWeight: 500,
  },
  skipButton: {
    width: 'fit-content',
    padding: 15,
    marginTop: 199.98,
    marginRight: 50,
    marginBottom: 50,
    justifySelf: 'flex-end',
    alignSelf: 'flex-end',
    backgroundColor: '#2980B9',
    borderRadius: 5,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
  },
  skipButtonText: {
    fontFamily: 'Lato-Regular',
    fontWeight: 700,
    fontSize: 13,
    color: '#fff',
    marginLeft: 30,
  },
  imageStyle: {
    position: 'relative',
    width: 28,
    height: 28,
    marginLeft: 24,
  }
});
